# action pour se baisser (voir description du format des actions)
# action pour se baisser

action: "CROUCH"
description:
  type: "{REPEATABLE}"
  count-of-repeat: "{INFINITE}"
  images: []
  keyboard:
    type: ["{SIMPLE}"]
    touch: "{ARROW-DOWN}"
    to-do: [
      "PLAYER_BODY_ACTION(CROUCH)"
    ]
  gamepad:
    type: ["{CONDITION}"]
    cond: [
      "INFERIOR({GAMEPAD_AXIS_LEFT_Y},0.7)"
    ]
    to-do: [
      "PLAYER_BODY_ACTION(CROUCH)"
    ]

description: [
  "IF(KEYBOARD_TOUCH_IS_PRESSED(ARROW_DOWN) OR INFERIOR({GAMEPAD_AXIS},0.7) )",
    "PLAYER_BODY_ACTION(CROUCH)",
  "ENDIF()"
]