# action pour se baisser (voir description du format des actions)
# action pour rouler au sol vers la gauche

action: "ROULADE_LEFT"
description:
  type: "{SIMPLE}"
  images: []
  keyboard:
    type: ["{COMBINED-TOUCH}","{SEQUENCE}"]
    touch: ["{ARROW-LEFT}","{ARROW-DOWN}"]
    sequence:
      step-1:
        pre-actions: [
          "STORE(FORMULA({PLAYER_X_POS} - 40),PLAYER_DST_X_POS_ROULADE_LEFT)"
        ]
        end-actions: [
          "FREE(PLAYER_DST_X_POS_ROULADE_LEFT)"
        ]
        images: []
        to-do: [
          "UPDATE({PLAYER_X_POS} ,FORMULA({PLAYER_X_POS} - 2))",
          "PLAYER_BODY_ACTION(CROUCH)"
        ]
        cond: [
          "INFERIOR({PLAYER_DST_X_POS_ROULADE_LEFT},{PLAYER_X_POS})"
        ]
  gamepad:
    type: ["{CONDITION}","{ SEQUENCE-REFERENCE }"]
    cond: [
      "INFERIOR({ GAMEPAD_AXIS_LEFT_X },-0.5)",
      "INFERIOR({ GAMEPAD_AXIS_LEFT_Y },-0.5)"
    ]
    sequence-reference: "../keyboard/sequence"
