# action pour se baisser (voir description du format des actions)
# action pour se déplacer sur la gauche

action: "GO_LEFT"
description:
  type: "{SIMPLE}"
  images: []
  touch-config:
    keyboard:
      type: ["{SIMPLE}"]
      touch: "{ARROW-LEFT}"
      to-do: [
        "UPDATE({PLAYER_POS_X},FORMULA({PLAYER_POS_X} - 10) )"
      ]
    gamepad:
      type: ["{ CONDITION }"]
      cond: ["INFERIOR({GAMEPAD_AXIS_LEFT_X},-0.3)"]
      to-do: [
        "UPDATE({PLAYER_POS_X},FORMULA({PLAYER_POS_X} - (({GAMEPAD_AXIS_LEFT_X} * -1) * 10) ) )"
      ]