# action pour se baisser (voir description du format des actions)
# action pour se déplacer sur la gauche

action: "GO_LEFT"
description:
  type: "{SIMPLE}"
  images: [1,2,1]
  touch-config:
    keyboard:
      type: ["{SIMPLE}"]
      touch: "{LEFT_ARROW"}
      to-do: [
        "{PLAYER_POS_X} = ({PLAYER_POS_X} - 10)"
      ]
    gamepad:
      type: ["{ CONDITION }"]
      cond: ["INFERIOR({GAMEPAD_AXIS_LEFT_X},-0.3)"]
      to-do: [
        "{PLAYER_POS_X} = ({PLAYER_POS_X} - (({GAMEPAD_AXIS_LEFT_X} * -1) * 10))"
      ]