# action pour se baisser (voir description du format des actions)
# action pour se déplacer à droite

action: "GO_RIGHT"
description:
  type: "{SIMPLE}"
  images: [1,2,1]
  touch-config:
    keyboard:
      type: ["{SIMPLE}"]
      touch: "{ARROW-LEFT}"
      to-do: [
        "UPDATE({PLAYER_POS_X} ,FORMULA(({PLAYER_POS_X} - 10)) )"
      ]
    gamepad:
      type: ["{ CONDITION }"]
      cond: ["SUPERIOR({ GAMEPAD_AXIS_LEFT_X },0.3)"]
      to-do: [
        "UPDATE({PLAYER_POS_X} ,FORMULA({PLAYER_POS_X} + ({GAMEPAD_AXIS_LEFT_X} * 10) ) )"
      ]