# action pour se baisser (voir description du format des actions)
# action pour sauter sur place

action: "STATIC_JUMP"
description:
  type: "{REPEATABLE}"
  count-of-repeat: 3
  images: [1,2,3]
  keyboard:
    type: ["{SIMPLE}"]
    touch: "{SPACE_BAR}"
    to-do: [
      "{PLAYER_POS_Y} = ({POS_REFERENCE_Y} + {PLAYER_POS_Y} + 10)"
    ]
  gamepad:
    type: ["{SIMPLE }"]
    touch: "{ GAMEPAD_X_TOUCH }"
    to-do: [
      "{PLAYER_POS_Y} = ({POS_REFERENCE_Y} + { PLAYER_POS_Y } + 10)"
    ]