# liste des images du personnage
images:
  position-debout:
    path: "/chemin/image-debout.png"
    contentConfig:
      - x: 0
        y: 0
        width: 200
        height: 300
      - x: 300
        y: 0
        width: 200
        height: 100
  marche:
    path: "/chemin/image-marche.png"
    contentConfig:
      - x: 0
        y: 0
        width: 200
        height: 300

# nom de base du personnage
name:

# énergie requise pour passer dans cette forme
energy: 0

# durée de la forme
duration: "{INFINITE}"

# formule de calcul du nombre de points donné par un combo
combo-gain-formula: "{COUNT_OF_HITS} * {ATTACK_SPEED}"

# points de vie de base du bouclier
shield-points: 300

# liste de clés des images nécessaires pour le bouclier
shield-images: []

# liste de clés des images nécessaires pour tomber
fell-images: []

# liste des images de victoire ( les listes ici je les ai pas défini en haut c''est pour le test)
victory-images: [
  ["victoire_image"],
  ["victoire_image_bleue_1","victoire_image_blue_2"],
  ["victoire_image_rouge"]
]

# images coup pris à la tête
head-hit-images: []

# images coup pris au corps
body-hit-images: []

# liste de clés des images nécessaires pour se relever
get-up-images: []

# liste des actions du personnages (permet le chargement partiel)
actions-map:
  crouch : "/config/forms/base-form/actions/crouch.yaml"
  go-left: "/config/forms/base-form/actions/go-left.yaml"
  go-right: "/config/forms/base-form/actions/go-right.yaml"
  jump-to-left: "/config/forms/base-form/actions/jump-to-left.yaml"
  jump-to-right : "/config/forms/base-form/actions/jump-to-right.yaml"
  roulade-left : "/config/forms/base-form/actions/roulade-left.yaml"
  roulade-right : "/config/forms/base-form/actions/roulade-right.yaml"
  static-jump: "/config/forms/base-form/actions/static-jump.yaml"
