# liste des images du personnage
images:
  1:
    path: "chemin/"
    contentConfig:

# nom de base du personnage
name: Nom du personnage

# énergie requise pour passer dans cette forme
energy: 0

# durée de la forme
duration: "{INFINITE}"

# vitesse d'attaque
attack-speed: 200

# formule de calcul du nombre de points donné par un combo
combo-gain-formula: "{COUNT_OF_HITS} * {ATTACK_SPEED}"

# points de vie de base du bouclier
shield-points: 300

# liste de clés des images nécessaires pour le bouclier
shield-images: []

# liste de clés des images nécessaires pour tomber
fell-images: []

# liste des images de victoire
victory-images: [
  [],
  []
]

# images coup pris à la tête
head-hit-images: []

# images coup pris au corps
body-hit-images: []

# liste de clés des images nécessaires pour se relever
get-up-images: []

# liste des actions du personnages (permet le chargement partiel)
actions-map:
  crouch : "/config/forms/base-form/actions/crouch.yaml"
  go-left: "/config/forms/base-form/actions/go-left.yaml"
  go-right: "/config/forms/base-form/actions/go-right.yaml"
  jump-to-left: "/config/forms/base-form/actions/jump-to-left.yaml"
  jump-to-right : "/config/forms/base-form/actions/jump-to-right.yaml"
  roulade-left : "/config/forms/base-form/actions/roulade-left.yaml"
  roulade-right : "/config/forms/base-form/actions/roulade-right.yaml"
  static-jump: "/config/forms/base-form/actions/static-jump.yaml"